from objects_normalizer.TypeCheckManager import TypeCheckManager
from objects_normalizer.objects_normalizer import ObjectsNormalizer
from .ObjectAttributes.AnyTypeAttribute import AnyTypeAttribute
from .ObjectAttributes.CustomTypeAttribute import CustomTypeAttribute
from .ObjectAttributes.DefaultDictTypeAttribute import DefaultDictTypeAttribute
from .ObjectAttributes.DictTypeAttribute import DictTypeAttribute
from .ObjectAttributes.IntTypeAttribute import IntTypeAttribute
from .ObjectAttributes.ListTypeAttribute import ListTypeAttribute
from .ObjectAttributes.OrderedDictTypeAttribute import OrderedDictTypeAttribute
from .ObjectAttributes.StrTypeAttribute import StrTypeAttribute
from .ObjectAttributes.TupleTypeAttribute import TupleTypeAttribute
from .ObjectAttributes.UnionTypeAttribute import UnionTypeAttribute


